### ISSUE TITLE
SGD-SVM Parameters

### ISSUE THREAD

**Issue by codingnoobneedshelp** [zygmuntz/sofia-ml-mod#2]
Hello,
i'm new to all of this and i apologize for this question.

I'm using the Sofia-ML SGD-SVM, as i understand it is the same like RankSVM but with SGD. Can you maybe explain me how parameters like:

Learning Options:
-c float -> C: trade-off between training error
and margin (default 0.01)
Kernel Options:
-t int -> type of kernel function:

are set in Sofia-ML? Are they set to default?

Thanks and Regards

**Comment by zygmuntz** [comment]
This would be a question for D. Sculley, the author of sofia-ml.
